version: "3.8"

services:
  frontend:
    build: ./expense-tracker-web-client
    image: "inzagher/expense-tracker-web-client:master"
    container_name: "expense-tracker-web-client"
    depends_on:
      - "backend"
    ports:
      - "80:80"
  backend:
    build: ./expense-tracker-server
    image: "inzagher/expense-tracker-server:master"
    container_name: "expense-tracker-server"
    depends_on:
      - "database"
    ports:
      - "8080:8080"
    volumes:
      - "backup-data:/opt/expense-tracker-server/backups"
    environment:
      - "SPRING_PROFILES_ACTIVE=default,scheduling-enabled"
      - "DATABASE_HOST=expense-tracker-database"
      - "DATABASE_PORT=5432"
      - "DATABASE_NAME=expenses"
      - "DATABASE_USERNAME=sa"
      - "DATABASE_PASSWORD=12345"
      - "BACKUP_DIRECTORY_PATH=backups"
      - "TZ=Europe/Moscow"
  database:
    container_name: "expense-tracker-database"
    image: "postgres:14-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=sa"
      - "POSTGRES_PASSWORD=12345"
      - "POSTGRES_DB=expenses"
      - "TZ=Europe/Moscow"
volumes:
  postgresql-data:
    name: "expense-tracker-database"
    external: false
  backup-data:
    name: "expense-tracker-backups"
    external: false