backup.directory: ${BACKUP_DIRECTORY_PATH:target/backups}
springdoc:
  swagger-ui.path: "/"
  webjars.prefix: ""
spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:expenses}"
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:12345}
  flyway:
    table: "migrations"
    locations: "classpath:database_migrations"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none
    show-sql: false