backup:
  directory: backups
spring:
  datasource:
    url: "jdbc:postgresql://postgresql-server:5432/expenses"
    username: sa
    password: 12345
  flyway:
    table: "migrations"
    locations: "classpath:db/migration"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none