backup:
  directory: target/backups
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/expenses_debug"
    username: sa
    password: 12345
  flyway:
    table: "migrations"
    locations: "classpath:db/migration"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none